### ISSUE TITLE
docker部署出错

### ISSUE THREAD

**Issue by saucer-man** [anyant/rssant#100]
按照文档操作，没有改任何参数。

环境debian10 Docker version 20.10.5, build 55c4c88

```
$ bash ~/rssant/start.sh
rssant-data
rssant-postgres-data
rssant-postgres-logs
Error: No such container: rssant
a70cdaa90c13fca8240931318a3921302f990fe7f9a2415e5bb29b06e5411f71
2021-04-17 03:31:47,689 INFO Set uid to user 0 succeeded
2021-04-17 03:31:47,760 INFO RPC interface 'supervisor' initialized
2021-04-17 03:31:47,760 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2021-04-17 03:31:47,760 INFO RPC interface 'supervisor' initialized
2021-04-17 03:31:47,760 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-04-17 03:31:47,760 INFO supervisord started with pid 1
2021-04-17 03:31:48,763 INFO spawned: 'api' with pid 10
2021-04-17 03:31:48,764 INFO spawned: 'async-api' with pid 11
2021-04-17 03:31:48,765 INFO spawned: 'harbor' with pid 12
2021-04-17 03:31:48,767 INFO spawned: 'initdb' with pid 13
2021-04-17 03:31:48,769 INFO spawned: 'nginx' with pid 14
2021-04-17 03:31:48,772 INFO spawned: 'postgres' with pid 15
2021-04-17 03:31:48,775 INFO spawned: 'scheduler' with pid 16
2021-04-17 03:31:48,778 INFO spawned: 'worker' with pid 18
+ /app/box/bin/wait-initdb.sh
+ rm -f /app/data/initdb.ready
2021-04-17 03:31:48,789 INFO success: initdb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
+ /app/box/bin/wait-initdb.sh
+ /app/box/bin/wait-initdb.sh
+ /app/box/bin/wait-initdb.sh
+ su - postgres -c 'while true; do /usr/bin/pg_isready; status=$?; if [[ $status -eq 0 ]]; then break; fi; sleep 1; done;'
+ /usr/sbin/nginx -g 'daemon off;'
+ /app/box/bin/wait-initdb.sh
++ ls -A /var/lib/postgresql/11/main
+ '[' '!' '' ']'
+ echo 'copy postgresql init data to mounted volume'
copy postgresql init data to mounted volume
+ cp -r /var/lib/postgresql/11/init/PG_VERSION /var/lib/postgresql/11/init/base /var/lib/postgresql/11/init/global /var/lib/postgresql/11/init/pg_commit_ts /var/lib/postgresql/11/init/pg_dynshmem /var/lib/postgresql/11/init/pg_logical /var/lib/postgresql/11/init/pg_multixact /var/lib/postgresql/11/init/pg_notify /var/lib/postgresql/11/init/pg_replslot /var/lib/postgresql/11/init/pg_serial /var/lib/postgresql/11/init/pg_snapshots /var/lib/postgresql/11/init/pg_stat /var/lib/postgresql/11/init/pg_stat_tmp /var/lib/postgresql/11/init/pg_subtrans /var/lib/postgresql/11/init/pg_tblspc /var/lib/postgresql/11/init/pg_twophase /var/lib/postgresql/11/init/pg_wal /var/lib/postgresql/11/init/pg_xact /var/lib/postgresql/11/init/postgresql.auto.conf /var/lib/postgresql/11/main
/var/run/postgresql:5432 - no response
+ rm -f /var/lib/postgresql/11/main/postmaster.pid
+ /usr/lib/postgresql/11/bin/postgres -D /var/lib/postgresql/11/main -c config_file=/etc/postgresql/11/main/postgresql.conf
2021-04-17 03:31:48.913 UTC [40] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-04-17 03:31:48.913 UTC [40] LOG:  listening on IPv6 address "::", port 5432
2021-04-17 03:31:48.919 UTC [40] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-04-17 03:31:48.933 UTC [41] LOG:  database system was shut down at 2020-04-19 06:34:02 UTC
2021-04-17 03:31:48.939 UTC [40] LOG:  database system is ready to accept connections
/var/run/postgresql:5432 - accepting connections
2021-04-17 03:31:49,888 INFO success: api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-17 03:31:49,889 INFO success: async-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-17 03:31:49,889 INFO success: harbor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-17 03:31:49,890 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-17 03:31:49,890 INFO success: postgres entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-17 03:31:49,890 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-17 03:31:49,891 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
+ su - postgres -c 'psql -f /app/box/initdb.sql'
CREATE ROLE
CREATE DATABASE
+ python manage.py runscript django_pre_migrate
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    import rssant_common.django_setup  # noqa:F401
  File "/app/rssant_common/django_setup.py", line 27, in <module>
    _django_setup()
  File "/app/rssant_common/django_setup.py", line 23, in _django_setup
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/app/rssant/settings/__init__.py", line 1, in <module>
    from .settings import *  # noqa: F401,F403
  File "/app/rssant/settings/settings.py", line 16, in <module>
    from rssant_config import CONFIG as ENV_CONFIG
  File "/app/rssant_config/__init__.py", line 1, in <module>
    from .env import CONFIG
  File "/app/rssant_config/env.py", line 185, in <module>
    CONFIG = load_env_config()
  File "/app/rssant_config/env.py", line 182, in load_env_config
    return EnvConfig(configs)
  File "/usr/local/lib/python3.7/site-packages/validr/model.py", line 160, in __init__
    raise ModelInvalid(errors)
validr._exception_c.ModelInvalid: 
+---------------+---------------------------------+
| Key           | Error                           |
+---------------+---------------------------------+
| rss_proxy_url | invalid or incorrect url format |
+---------------+---------------------------------+
```

其中rss_proxy_url没有改配置，enable值为false

**Comment by guyskk** [comment]
感谢反馈，rss_proxy_url 需要设置为空值或者有效的URL格式。
文档里的示例需要对照说明改一下，我也更新了一下文档：https://github.com/anyant/rssant/commit/a5b2536ea6c5263ae37aade5bba1addf383e39ca
